/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MiaoAlertTipProvider: typeof import('./src/components/miaoAlertTipProvider.vue')['default']
    MiaoContextMenu: typeof import('./src/components/miaoContextMenu.vue')['default']
    MiaoDraggableDiv: typeof import('./src/components/miaoDraggableDiv.vue')['default']
    MiaoDropHandler: typeof import('./src/components/miaoDropHandler.vue')['default']
    MiaoLazyDiv: typeof import('./src/components/miaoLazyDiv.vue')['default']
    MiaoMask: typeof import('./src/components/miaoMask.vue')['default']
    MiaoPopupInput: typeof import('./src/components/miaoPopupInput.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NQrCode: typeof import('naive-ui')['NQrCode']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ShareQrCodeCard: typeof import('./src/components/APP/ShareQrCodeCard.vue')['default']
    ViewContainer: typeof import('./src/components/APP/ViewContainer.vue')['default']
    ViewController: typeof import('./src/components/APP/ViewController.vue')['default']
  }
}
