/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MiaoAlertTipProvider: typeof import('./src/components/miaoAlertTipProvider.vue')['default']
    MiaoContextMenu: typeof import('./src/components/miaoContextMenu.vue')['default']
    MiaoDraggableDiv: typeof import('./src/components/miaoDraggableDiv.vue')['default']
    MiaoDropHandler: typeof import('./src/components/miaoDropHandler.vue')['default']
    MiaoLazyDiv: typeof import('./src/components/miaoLazyDiv.vue')['default']
    MiaoMask: typeof import('./src/components/miaoMask.vue')['default']
    MiaoPopupInput: typeof import('./src/components/miaoPopupInput.vue')['default']
    ShareQrCodeCard: typeof import('./src/components/APP/ShareQrCodeCard.vue')['default']
    ViewContainer: typeof import('./src/components/APP/ViewContainer.vue')['default']
    ViewController: typeof import('./src/components/APP/ViewController.vue')['default']
  }
}
